AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  
  clamavfn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clamavfn
      PackageType: Image
      Description: Runs a container of ClamAV to either scan files on EFS or update the virus definition database on EFS
      Timeout: 300
      MemorySize: 2048
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonElasticFileSystemFullAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue ESGPOCStack-MFTDMZSecurityGroup
        SubnetIds:
          - !ImportValue vpc-stack-DMZSUBNET1A
          - !ImportValue vpc-stack-DMZSUBNET1B
      FileSystemConfigs:
        - Arn: !ImportValue ESGPOCStack-DMSEFSCLAMAVAP
          LocalMountPath: /mnt/dmzefs
    Metadata:
      DockerTag: virus-scanner
      DockerContext: .
      Dockerfile: Dockerfile