AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  vpcstackDMZSUBNET1A:
    Type: String
    Default: subnet-062c6cea0b9281693
  vpcstackDMZSUBNET1B:
    Type: String
    Default: subnet-0b5c1a5bc7ead824f

Resources:
  
  clamavfn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: clamavfn
      PackageType: Image
      Description: Runs a container of ClamAV to either scan files on EFS or update the virus definition database on EFS
      Role: "arn:aws-us-gov:iam::227474134366:role/clamavfnRole"
      Timeout: 300
      MemorySize: 2048
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambda_ReadOnlyAccess
        - AWSXrayWriteOnlyAccess
        - AmazonElasticFileSystemFullAccess
        - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
      VpcConfig:
        SecurityGroupIds:
          - !ImportValue ESGStack-MFTDMZSecurityGroup
        SubnetIds:
          - !Ref vpcstackDMZSUBNET1A
          - !Ref vpcstackDMZSUBNET1B
      FileSystemConfigs:
        - Arn: !ImportValue ESGStack-DMSEFSCLAMAVAP
          LocalMountPath: /mnt/dmzefs
    Metadata:
      DockerTag: virus-scanner
      DockerContext: .
      Dockerfile: Dockerfile

  DefinitionUpdateEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Rule for Amazon CloudWatch Events to trigger a definition update
      ScheduleExpression: "rate(1 hour)"
      State: ENABLED
      Targets:
      - Arn: !GetAtt clamavfn.Arn
        Id: DefinitionUpdateEvent
        Input: '{"operation":"update","filename":"placeholdervalue"}'

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt clamavfn.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt DefinitionUpdateEvent.Arn